@startuml "Système de Gestion RH d'une Entreprise"
left to right direction
actor "Agent RH" as Agent
actor "Manager" as Manager
actor "Candidat" as Candidat


rectangle "Système de Gestion RH d'une Entreprise" {
    rectangle "Système de gestion des Favoris" {
        usecase "Gérer les favoris" as UC1
        usecase "Consulter fonctionnalités favoris" as UC1_1
        usecase "Ajouter fonctionnalité au favoris" as UC1_2
        usecase "Supprimer fonctionnalité au favoris" as UC1_3
        usecase "Remettre les fonctionnalités par défaut" as UC1_4
        usecase "Rechercher fonctionnalité" as UC1_5
    }
    rectangle "Système de Gestion des Tables"{
        usecase "Gérer les tables" as UC2
        usecase "Gérer les employés" as UC2_1
        usecase "Ajouter un employé" as UC2_1_1
        usecase "Modifier un employé" as UC2_1_2
        usecase "Supprimer un employé" as UC2_1_3
        usecase "Rechercher un employé" as UC2_1_4
        usecase "Consulter un employé" as UC2_1_5
        usecase "Imprimer un employé" as UC2_1_6

        usecase "Gérer les services" as UC2_2
        usecase "Ajouter un service" as UC2_2_1
        usecase "Modifier un service" as UC2_2_2
        usecase "Supprimer un service" as UC2_2_3
        usecase "Rechercher un service" as UC2_2_4
        usecase "Consulter un service" as UC2_2_5
        usecase "Imprimer un service" as UC2_2_6

        usecase "Gérer les congés" as UC2_3
        usecase "Ajouter un congé" as UC2_3_1
        usecase "Modifier un congé" as UC2_3_2
        usecase "Supprimer un congé" as UC2_3_3
        usecase "Rechercher un congé" as UC2_3_4
        usecase "Consulter un congé" as UC2_3_5
        usecase "Imprimer un congé" as UC2_3_6

        usecase "Gérer les contrats" as UC2_4
        usecase "Ajouter un contrat" as UC2_4_1
        usecase "Modifier un contrat" as UC2_4_2
        usecase "Supprimer un contrat" as UC2_4_3
        usecase "Rechercher un contrat" as UC2_4_4
        usecase "Consulter un contrat" as UC2_4_5
        usecase "Imprimer un contrat" as UC2_4_6

        usecase "Gérer les salaires" as UC2_5
        usecase "Ajouter un salaire" as UC2_5_1
        usecase "Modifier un salaire" as UC2_5_2
        usecase "Supprimer un salaire" as UC2_5_3
        usecase "Rechercher un salaire" as UC2_5_4
        usecase "Consulter un salaire" as UC2_5_5
        usecase "Imprimer un salaire" as UC2_5_6

        usecase "Gérer les recrutements" as UC2_6
        usecase "Ajouter un recrutement" as UC2_6_1
        usecase "Modifier un recrutement" as UC2_6_2
        usecase "Supprimer un recrutement" as UC2_6_3
        usecase "Rechercher un recrutement" as UC2_6_4
        usecase "Consulter un recrutement" as UC2_6_5
        usecase "Imprimer un recrutement" as UC2_6_6
    }
    rectangle "Système de Gestion des Employés" {
        usecase "Consulter fiche employé" as UC3_1
        usecase "Consulter rapport de performance" as UC3_2
        usecase "Evaluer employé" as UC3_3
        usecase "Rechercher rapport de performance" as UC3_4
        usecase "Générer un rapport de performance" as UC3_5
    }
    rectangle "Système de Gestion des Congés"{
        usecase "Donner congé" as UC4 
        usecase "Donner congé annuel" as UC4_1
        usecase "Donner congé maladie" as UC4_2
        usecase "Donner congé paternité/maternité" as UC4_3
        usecase "Donner congé sans solde" as UC4_4
        usecase "Suivre solde congé" as UC5
    }
    rectangle "Système de Gestion des Salaires et de la Paie"{

    }
    rectangle "Système de Gestion des Contrats"{

    }
    rectangle "Système d'Evaluation des Performances"{

    }
    rectangle "Système de Gestion des Recrutements"{

    }
    rectangle "Système de Gestion d'Analyse et Tableaux de bord"{

    }
    rectangle "Système des Gestion Comptes"{

    }
}
Agent --> UC1

UC1 <|-- UC1_1 : <<extends>>
UC1 <|-- UC1_2 : <<extends>>
UC1 <|-- UC1_3 : <<extends>>
UC1 <|-- UC1_4 : <<extends>>
UC1 <|-- UC1_5 : <<extends>>
UC1_1 --> UC1_5 : <<includes>>
UC1_2 --> UC1_5 : <<includes>>
UC1_3 --> UC1_5 : <<includes>>
UC1_4 --> UC1_5 : <<includes>>


Agent --> UC2

UC2 <|-- UC2_1 : <<extends>>

UC2_1 <|-- UC2_1_1 : <<extends>>
UC2_1 <|-- UC2_1_2 : <<extends>>
UC2_1 <|-- UC2_1_3 : <<extends>>
UC2_1 <|-- UC2_1_4 : <<extends>>
UC2_1 <|-- UC2_1_5 : <<extends>>
UC2_1 <|-- UC2_1_6 : <<extends>>
UC2_1_1 --> UC2_1_4 : <<includes>>
UC2_1_2 --> UC2_1_4 : <<includes>>
UC2_1_3 --> UC2_1_4 : <<includes>>
UC2_1_4 --> UC2_2_4 : <<includes>>
UC2_1_5 --> UC2_1_4 : <<includes>>
UC2_1_6 --> UC2_1_4 : <<includes>>


UC2 <|-- UC2_2 : <<extends>>

UC2_2 <|-- UC2_2_1 : <<extends>>
UC2_2 <|-- UC2_2_2 : <<extends>>
UC2_2 <|-- UC2_2_3 : <<extends>>
UC2_2 <|-- UC2_2_4 : <<extends>>
UC2_2 <|-- UC2_2_5 : <<extends>>
UC2_2 <|-- UC2_2_6 : <<extends>>
UC2_2_1 --> UC2_2_4 : <<includes>
UC2_2_2 --> UC2_2_4 : <<includes>>
UC2_2_3 --> UC2_2_4 : <<includes>>
UC2_2_5 --> UC2_2_4 : <<includes>>
UC2_2_6 --> UC2_2_4 : <<includes>>

UC2 <|-- UC2_3 : <<extends>>

UC2_3 <|-- UC2_3_1 : <<extends>>
UC2_3 <|-- UC2_3_2 : <<extends>>
UC2_3 <|-- UC2_3_3 : <<extends>>
UC2_3 <|-- UC2_3_4 : <<extends>>
UC2_3 <|-- UC2_3_5 : <<extends>>
UC2_3 <|-- UC2_3_6 : <<extends>>
UC2_3_1 --> UC2_3_4 : <<includes>>
UC2_3_2 --> UC2_3_4 : <<includes>>
UC2_3_3 --> UC2_3_4 : <<includes>>
UC2_3_4 --> UC2_1_4 : <<includes>>
UC2_3_5 --> UC2_3_4 : <<includes>>
UC2_3_6 --> UC2_3_4 : <<includes>>


UC2 <|-- UC2_4 : <<extends>>

UC2_4 <|-- UC2_4_1 : <<extends>>
UC2_4 <|-- UC2_4_2 : <<extends>>
UC2_4 <|-- UC2_4_3 : <<extends>>
UC2_4 <|-- UC2_4_4 : <<extends>>
UC2_4 <|-- UC2_4_5 : <<extends>>
UC2_4 <|-- UC2_4_6 : <<extends>>
UC2_4_1 --> UC2_4_4 : <<includes>>
UC2_4_2 --> UC2_4_4 : <<includes>>
UC2_4_3 --> UC2_4_4 : <<includes>>
UC2_4_4 --> UC2_1_4 : <<includes>>
UC2_4_5 --> UC2_4_4 : <<includes>>
UC2_4_6 --> UC2_4_4 : <<includes>>

UC2 <|-- UC2_5 : <<extends>>

UC2_5 <|-- UC2_5_1 : <<extends>>
UC2_5 <|-- UC2_5_2 : <<extends>>
UC2_5 <|-- UC2_5_3 : <<extends>>
UC2_5 <|-- UC2_5_4 : <<extends>>
UC2_5 <|-- UC2_5_5 : <<extends>>
UC2_5 <|-- UC2_5_6 : <<extends>>
UC2_5_1 --> UC2_5_4 : <<includes>>
UC2_5_2 --> UC2_5_4 : <<includes>>
UC2_5_3 --> UC2_5_4 : <<includes>>
UC2_5_4 --> UC2_1_4 : <<includes>>
UC2_5_5 --> UC2_5_4 : <<includes>>
UC2_5_6 --> UC2_5_4 : <<includes>>

UC2 <|-- UC2_6 : <<extends>>

UC2_6 <|-- UC2_6_1 : <<extends>>
UC2_6 <|-- UC2_6_2 : <<extends>>
UC2_6 <|-- UC2_6_3 : <<extends>>
UC2_6 <|-- UC2_6_4 : <<extends>>
UC2_6 <|-- UC2_6_5 : <<extends>>
UC2_6 <|-- UC2_6_6 : <<extends>>
UC2_6_1 --> UC2_6_4 : <<includes>>
UC2_6_2 --> UC2_6_4 : <<includes>>
UC2_6_3 --> UC2_6_4 : <<includes>>
UC2_6_4 --> UC2_1_4 : <<includes>>
UC2_6_5 --> UC2_6_4 : <<includes>>
UC2_6_6 --> UC2_6_4 : <<includes>>


Agent --> UC3_1
Agent --> UC3_2
Manager --> UC3_2
Manager --> UC3_3

UC3_1 --> UC2_1_4 : <<includes>>
UC3_2 --> UC2_1_4 : <<includes>>
UC3_3 --> UC2_1_4 : <<includes>>
UC3_2 --> UC3_4 : <<includes>>
UC3_4 --> UC2_1_4 : <<includes>>
UC3_5 --> UC3_4 : <<includes>>
UC3_3 <|-- UC3_5 : <<extends>>


Agent --> UC4
Agent --> UC5
UC4 --> UC2_3_1 : <<includes>>
UC4_1 --|> UC4
UC4_2 --|> UC4
UC4_3 --|> UC4
UC4_4 --|> UC4
UC5 --> UC2_3_4 : <<includes>>
UC5 --> UC2_5_4 : <<includes>>

@enduml