# Generated by Django 5.1.4 on 2025-01-19 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_created_at', models.DateTimeField(auto_now_add=True)),
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_email', models.EmailField(max_length=255)),
                ('account_password', models.CharField(max_length=255)),
                ('account_role', models.CharField(choices=[('c', 'Candidat'), ('e', 'Employé'), ('m', 'Manager'), ('a', 'Agent')], default='c', max_length=1)),
                ('account_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_birth_date', models.DateField()),
                ('user_country', models.CharField(max_length=50)),
                ('user_city', models.CharField(max_length=50)),
                ('user_commune', models.CharField(max_length=50)),
                ('user_street', models.CharField(max_length=255)),
                ('user_phone', models.CharField(max_length=10)),
                ('user_profile_pic', models.ImageField(blank=True, default=None, null=True, upload_to='profile_pics/')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.account')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('formation_id', models.AutoField(primary_key=True, serialize=False)),
                ('formation_institution', models.CharField(max_length=100)),
                ('formation_nom', models.CharField(max_length=100)),
                ('formation_start_date', models.DateField()),
                ('formation_end_date', models.DateField()),
                ('formation_is_justified', models.BooleanField(default=False)),
                ('formation_justification', models.FileField(blank=True, default=None, null=True, upload_to='justifications/formations/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('experience_company', models.CharField(max_length=100)),
                ('experience_position', models.CharField(max_length=100)),
                ('experience_start_date', models.DateField()),
                ('experience_end_date', models.DateField()),
                ('experience_is_justified', models.BooleanField(default=False)),
                ('experience_justification', models.FileField(blank=True, default=None, null=True, upload_to='justifications/experiences/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('competence_id', models.AutoField(primary_key=True, serialize=False)),
                ('competence_name', models.CharField(max_length=50)),
                ('competence_is_justified', models.BooleanField(default=False)),
                ('competence_justification', models.FileField(blank=True, default=None, null=True, upload_to='justifications/competences/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
