# Generated by Django 5.1.4 on 2025-01-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
