# Generated by Django 5.1.4 on 2025-01-21 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_account_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonctionnalite',
            fields=[
                ('fonctionnalite_id', models.AutoField(primary_key=True, serialize=False)),
                ('fonctionnalite_titre', models.CharField(max_length=50)),
                ('fonctionnalite_logo', models.CharField(max_length=50)),
                ('fonctionnalite_lien', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('favoris_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fonctionnalite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.fonctionnalite')),
            ],
        ),
    ]
