# Generated by Django 5.1.4 on 2025-01-21 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_fonctionnalite_favoris'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favoris',
            new_name='Favori',
        ),
    ]
